### ISSUE TITLE
No such file or directory: 'data/2011 Census Microdata Teaching File.csv'

### ISSUE THREAD

**Issue by hmsklv0** [alan-turing-institute/privacy-sdg-toolbox#132]
(tapas) [root@localhost examples]# python3 multiple_attacks.py 
Traceback (most recent call last):
  File "/root/bishe/17tapas/tapas/examples/multiple_attacks.py", line 23, in <module>
    data = tapas.datasets.TabularDataset.read(
  File "/root/bishe/17tapas/tapas/tapas/datasets/dataset.py", line 263, in read
    return _parse_csv(f"{filepath}.csv", schema, label or filepath)
  File "/root/bishe/17tapas/tapas/tapas/datasets/dataset.py", line 37, in _parse_csv
    data = pd.read_csv(fp, header=validate_header(fp, cnames), dtype=dtypes, index_col=None, names=cnames)    
  File "/root/bishe/17tapas/tapas/tapas/datasets/dataset.py", line 77, in validate_header
    row0 = pd.read_csv(fp, header=None, index_col=None, nrows=1) 
  File "/data/tool_packages/ENTER/envs/tapas/lib/python3.9/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/data/tool_packages/ENTER/envs/tapas/lib/python3.9/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/data/tool_packages/ENTER/envs/tapas/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/data/tool_packages/ENTER/envs/tapas/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/data/tool_packages/ENTER/envs/tapas/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/data/tool_packages/ENTER/envs/tapas/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1735, in _make_engine
    self.handles = get_handle(
  File "/data/tool_packages/ENTER/envs/tapas/lib/python3.9/site-packages/pandas/io/common.py", line 856, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/2011 Census Microdata Teaching File.csv'

**Comment by hmsklv0** [comment]
I can't find this file
